# FUNDING.yml - Supernova
# Configuración de financiación para GitHub.

# GitHub Sponsors
github: glastor-dev

# URLs personalizadas (Redirige a la sección de Sponsor del README para ver Alias y ACH)
custom:
  - https://github.com/sponsors/glastor-dev
